# Generated by Django 5.2.4 on 2025-07-19 13:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRoadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='RoadmapNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('position_x', models.FloatField(default=0)),
                ('position_y', models.FloatField(default=0)),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='roadmap.courseroadmap')),
            ],
        ),
        migrations.CreateModel(
            name='RoadmapEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='out_edges', to='roadmap.roadmapnode')),
                ('to_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_edges', to='roadmap.roadmapnode')),
            ],
        ),
        migrations.CreateModel(
            name='RoadmapResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('type', models.CharField(choices=[('article', 'Article'), ('video', 'Video'), ('book', 'Book'), ('course', 'Course'), ('docs', 'Documentation'), ('other', 'Other')], max_length=20)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='roadmap.roadmapnode')),
            ],
        ),
    ]
