# Generated by Django 5.2.4 on 2025-07-19 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmapnode',
            name='dependencies',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
